Repository electron/electronjs.org, pull requests merged in 2019-04, with the labels that each got.

#2314 docs(blog): add from-native-to-js
  data/blog/from-native-to-js.md
Labels: blog

#2373 feat: update footer to `@primer/css`
  public/styles/_base.scss
  public/styles/helpers/_footer.scss
  views/partials/footer.html
Labels: ready-for-review

#2356 feat: update languages page to `@primer/css`
  cypress/integration/actions.js
  views/languages/index.html
Labels: ready-for-review

#2355 feat: Update apps page to `@primer/css`
  public/styles/_app.scss
  views/apps/index.html
  views/apps/show.html
Labels: ready-for-review

#2402 feat: Anchor links - html script to js
  scripts/anchor-links.js
  scripts/index.js
  views/layouts/main.html
  views/partials/anchor_links.html
Labels: ready-for-review

#2388 feat: update Blog page to `@primer/css`
  cypress/integration/actions.js
  public/styles/_blog.scss
  views/blog/index.html
  views/blog/show.html
  views/layouts/post.html
  views/partials/blog_byline.html
Labels: ready-for-review

#2424 fix: don't show filter app bar when we on mobile
  public/styles/_app.scss
  views/apps/index.html
Labels: ready-for-review

#2399 feat: Update docs page to `@primer/css`
  cypress/integration/actions.js
  public/styles/_base.scss
  public/styles/_docs.scss
  public/styles/hljs/overrides.scss
  scripts/anchor-links.js
  scripts/index.js
  views/docs/index.html
  views/layouts/docs.html
  views/layouts/main.html
  views/partials/anchor_links.html
  views/partials/doc.html
Labels: ready-for-review

#1702 feat: create Electron 5.0 blog post
  data/blog/electron-5-0.md
Labels: wip

#2467 fix: Current pagination link color to white
  public/styles/helpers/_pagination.scss
Labels: ready-for-review

#2346 feat: update homepage to `@primer/css`
  public/styles/_home.scss
  public/styles/_releases.scss
  public/styles/_versions.scss
  public/styles/helpers/_icons.scss
  views/home.html
Labels: ready-for-review
